CREATE DATABASE PEDIDOS;

SHOW DATABASES;

USE PEDIDOS;

CREATE TABLE PEDIDOS.CLIENTES(
CLIENTEID INT AUTO_INCREMENT,
NOME VARCHAR (255) NOT NULL,
EMAIL TEXT (225) NOT NULL UNIQUE,
TELEFONE VARCHAR (26) NOT NULL,
PRIMARY KEY(CLIENTEID)
);

CREATE TABLE PEDIDOS.PEDIDO(
PEDIDOID INT AUTO_INCREMENT PRIMARY KEY,
CLIENTEID INT not null ,
DATAPEDIDO DATE  NOT NULL,
VALORTOTAL FLOAT NOT NULL ,
FOREIGN KEY (CLIENTEID) REFERENCES PEDIDOS.CLIENTES(CLIENTEID)
);

SHOW TABLES;

INSERT INTO PEDIDOS.CLIENTES (NOME, EMAIL, TELEFONE) VALUES ('ANA CORTES','ANA@gmail.com', '71 987526439');
INSERT INTO PEDIDOS.CLIENTES (NOME, EMAIL, TELEFONE) VALUES ('MANUEL TAVARES','MANU@gmail.com', '71 987629439');
INSERT INTO PEDIDOS.CLIENTES (NOME, EMAIL, TELEFONE) VALUES ('GUSTAVO CORREIA','GUGA@gmail.com', '71 993526489');
INSERT INTO PEDIDOS.CLIENTES (NOME, EMAIL, TELEFONE) VALUES ('LEA CORTES','LEA@gmail.com', '71 984527589');
INSERT INTO PEDIDOS.CLIENTES (NOME, EMAIL, TELEFONE) VALUES ('REBECA MORAIS','BECA@gmail.com', '71 993528745');

INSERT INTO PEDIDOS.PEDIDO (CLIENTEID, DATAPEDIDO, VALORTOTAL) VALUES ( 1 ,'2023-09-08', 740.00);
INSERT INTO PEDIDOS.PEDIDO (CLIENTEID, DATAPEDIDO, VALORTOTAL) VALUES (2,'2022-04-06', 4100.00);
INSERT INTO PEDIDOS.PEDIDO (CLIENTEID, DATAPEDIDO, VALORTOTAL) VALUES (3,'2020-10-02', 1750.00);
INSERT INTO PEDIDOS.PEDIDO (CLIENTEID, DATAPEDIDO, VALORTOTAL) VALUES (4,'2021-12-30', 800.00);
INSERT INTO PEDIDOS.PEDIDO (CLIENTEID, DATAPEDIDO, VALORTOTAL) VALUES (5,'2021-01-06', 9751.00);

SELECT * FROM PEDIDOS.CLIENTES;
SELECT * FROM PEDIDOS.PEDIDO;

-- FIZ BESTEIRA E TIVE QUE APAGAR KKK
DELETE FROM pedido WHERE CLIENTEID = 1;